databases:
  - name: fpl-moneyballdb
    plan: free
    databaseName: fpl-moneyball
    user: fpl-moneyball

services:
  - type: web
    plan: free
    name: fpl-moneyball
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fpl-moneyball.asgi:application -k uvicorn.workers.UvicornWorker"
    rootDir: fpl-moneyball
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fpl-moneyballdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
