databases:
  - name: fplmoneyballdb
    plan: free
    databaseName: fplmoneyballdb
    user: fplmoneyballdb

services:
  - type: web
    plan: free
    name: fpl-moneyball
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fpl-moneyball.asgi:application -k uvicorn.workers.UvicornWorker"
    rootDir: fpl-moneyball
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fplmoneyballdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
